version: "3"
services:
  api:
    build: .
    depends_on:
      - postgres
    ports:
      - 8000:8000
    volumes:
      - ./:/usr/src/app:ro
    command: uvicorn app.main:app --host 127.0.0.1 --reload
    env_file:
      - ./.env
    # environment:
    #   - DATABASE_HOSTNAME=
    #   - DATABASE_PORT=
    #   - DATABASE_PASSWORD=
    #   - DATABASE_NAME=
    #   - DATABASE_USERNAME=
    #   - SECRET_KEY=
    #   - ALGORITHM=
    #   - ACCESS_TOKEN_EXPIRE_MINUTES=

  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=APIdatabase
    volumes:
      - postgres-db:/var/lib/postgresql/data

volumes:
  postgres-db:
