name: Build and Deploy Code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3
      - name: install python version 3.10
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.10' 
      - run: python my_script.py


