name: Build and Deploy Code
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: [push, pull]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repository
        uses: actions/checkout@v3
      - name: sauin
        run: echo 'hola'


